# Generated by Django 2.2.10 on 2021-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=60, null=True)),
                ('Select_Blood_Group', models.CharField(blank=True, max_length=60, null=True)),
                ('District', models.CharField(blank=True, max_length=60, null=True)),
                ('Last_Donate_Date', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
