# Generated by Django 2.2.10 on 2021-02-17 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addDonors', '0002_auto_20210217_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donorinfo',
            options={'ordering': ('-uploaded_at',)},
        ),
        migrations.AddField(
            model_name='donorinfo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
